###
# @name spieler
POST http://localhost:8080/command
Content-Type: application/json
Accept: application/json

{
  "command": "SpielerPunktet"
}
###

# @name gegner
POST http://localhost:8080/command
Content-Type: application/json
Accept: application/json

{
  "command": "GegnerPunktet"
}
###

