# @name spieler
POST http://localhost:8080/command
Content-Type: application/json
Accept: application/json

{
  "command": "SpielerPunktet",
  "commandId": "{{$uuid}}",
  "aggregateId": "c2a36eac-0c8f-11f0-9cd2-0242ac120002",
  "data": {
    "createdAt": "{{$isoTimestamp}}"
  }
}

> {%
    client.assert(response.status === 202, "invalid response status")
%}
###




# @name gegner
POST http://localhost:8080/command
Content-Type: application/json
Accept: application/json

{
  "command": "GegnerPunktet",
  "commandId": "{{$uuid}}",
  "aggregateId": "c2a36eac-0c8f-11f0-9cd2-0242ac120002",
  "data": {
    "createdAt": "{{$isoTimestamp}}"
  }
}

> {%
    client.assert(response.status === 202, "invalid response status")
%}
###
